FROM pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-gpu.txt requirements.txt ./
RUN pip install --no-cache-dir -r requirements-gpu.txt

COPY . .

CMD ["python", "worker.py"]
