"""CSRF protection — double-submit pattern (stateless).

The CSRF token is derived from the authenticated session id (see auth.derive_csrf_token)
and injected into ``request.state.csrf_token`` by the auth middleware in main.py.

POST forms include a hidden ``_csrf`` field (generated by the template using
``request.state.csrf_token``).  HTMX mutating requests send it as an
``X-CSRF-Token`` header, configured via the meta tag + hx-headers in base.html.

Usage in route handlers that mutate state:

    from app.csrf import require_csrf

    @router.post("/some/path")
    def my_handler(
        ...
        _: None = Depends(require_csrf),
    ):
        ...
"""
import hmac

from fastapi import Depends, Form, Header, HTTPException, Request


async def require_csrf(
    request: Request,
    form_csrf: str = Form(default="", alias="_csrf"),
    header_csrf: str = Header(default="", alias="X-CSRF-Token"),
) -> None:
    """Validate the CSRF token submitted in a form field or HTTP header.

    Raises HTTP 403 if the token is absent or does not match the expected
    session-derived value stored in ``request.state.csrf_token``.
    """
    expected: str = getattr(request.state, "csrf_token", "")
    submitted: str = form_csrf or header_csrf

    if not expected or not submitted:
        raise HTTPException(status_code=403, detail="CSRF token missing")
    if not hmac.compare_digest(submitted, expected):
        raise HTTPException(status_code=403, detail="CSRF token invalid")
